#
# .travis.yaml contains YAML-formatted (http://www.yaml.org/) build
# instructions for continuous integration via Travis CI
# (http://docs.travis-ci.com/).
#

language: python

python:
    - "3.8"
    - "3.12"

env:
    global:
        - BEANSTALKD=./beanstalkd

install:
    # Deactivate the virtualenv enabled by `language: python`.
    - deactivate
    # Install most recent beanstalkd from source
    - wget https://github.com/kr/beanstalkd/archive/v1.10.tar.gz
    - tar xf v1.10.tar.gz
    - make -C beanstalkd-1.10/
    - mv beanstalkd-1.10/beanstalkd .
    # Bootstrap easy_install ...
    - wget -O /tmp/ez_setup.py $ST
    - sudo python$PYV /tmp/ez_setup.py
    # ... to use easy_install to install pip (1.1 works on 2.4) ...
    - sudo easy_install-$PYV pip==1.1
    # ... to use pip to install beanstalkc's dependencies ...
    - sudo pip-$PYV install http://pyyaml.org/download/pyyaml/PyYAML-3.09.tar.gz
    # ... and tes testing dependencies.
    - sudo pip-$PYV install nose

script: nosetests-$PYV -c .nose.cfg

branches:
    only:
        - master
